name: Build and Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  setup-build-bucket:
    name: Setup, Build, and push to Google Cloud Bucket
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn build
